apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          command: ["redis-server"]
          args: ["--replicaof", "redis-master", "6379"]
          resources:
            requests:
              cpu: "10m"
              memory: "12Mi"
            limits:
              cpu: "20m"
              memory: "25Mi"
              