apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      scrape_timeout: 4s

    scrape_configs:
      - job_name: 'redis-node'
        scrape_interval: 5s
        scrape_timeout: 4s
        static_configs:
          - targets: ['redis-node:8080']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.default.svc.cluster.local:8080']
